// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: components.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The primitive types of a field
type PrimitiveFieldType int32

const (
	// First are the not nullable, and then the nullable, this is to be
	// able to get the nullability of the type by the NULL_INT value
	PrimitiveFieldType_INT         PrimitiveFieldType = 0
	PrimitiveFieldType_STRING      PrimitiveFieldType = 1
	PrimitiveFieldType_CHAR        PrimitiveFieldType = 2
	PrimitiveFieldType_BOOL        PrimitiveFieldType = 3
	PrimitiveFieldType_DATE        PrimitiveFieldType = 4
	PrimitiveFieldType_NULL_INT    PrimitiveFieldType = 5
	PrimitiveFieldType_NULL_STRING PrimitiveFieldType = 6
	PrimitiveFieldType_NULL_CHAR   PrimitiveFieldType = 7
	PrimitiveFieldType_NULL_BOOL   PrimitiveFieldType = 8
	PrimitiveFieldType_NULL_DATE   PrimitiveFieldType = 9
)

// Enum value maps for PrimitiveFieldType.
var (
	PrimitiveFieldType_name = map[int32]string{
		0: "INT",
		1: "STRING",
		2: "CHAR",
		3: "BOOL",
		4: "DATE",
		5: "NULL_INT",
		6: "NULL_STRING",
		7: "NULL_CHAR",
		8: "NULL_BOOL",
		9: "NULL_DATE",
	}
	PrimitiveFieldType_value = map[string]int32{
		"INT":         0,
		"STRING":      1,
		"CHAR":        2,
		"BOOL":        3,
		"DATE":        4,
		"NULL_INT":    5,
		"NULL_STRING": 6,
		"NULL_CHAR":   7,
		"NULL_BOOL":   8,
		"NULL_DATE":   9,
	}
)

func (x PrimitiveFieldType) Enum() *PrimitiveFieldType {
	p := new(PrimitiveFieldType)
	*p = x
	return p
}

func (x PrimitiveFieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrimitiveFieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_components_proto_enumTypes[0].Descriptor()
}

func (PrimitiveFieldType) Type() protoreflect.EnumType {
	return &file_components_proto_enumTypes[0]
}

func (x PrimitiveFieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrimitiveFieldType.Descriptor instead.
func (PrimitiveFieldType) EnumDescriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{0}
}

type FieldTypeInformation_FieldType int32

const (
	FieldTypeInformation_PRIMITIVE FieldTypeInformation_FieldType = 0
	FieldTypeInformation_REFERENCE FieldTypeInformation_FieldType = 1
)

// Enum value maps for FieldTypeInformation_FieldType.
var (
	FieldTypeInformation_FieldType_name = map[int32]string{
		0: "PRIMITIVE",
		1: "REFERENCE",
	}
	FieldTypeInformation_FieldType_value = map[string]int32{
		"PRIMITIVE": 0,
		"REFERENCE": 1,
	}
)

func (x FieldTypeInformation_FieldType) Enum() *FieldTypeInformation_FieldType {
	p := new(FieldTypeInformation_FieldType)
	*p = x
	return p
}

func (x FieldTypeInformation_FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldTypeInformation_FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_components_proto_enumTypes[1].Descriptor()
}

func (FieldTypeInformation_FieldType) Type() protoreflect.EnumType {
	return &file_components_proto_enumTypes[1]
}

func (x FieldTypeInformation_FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldTypeInformation_FieldType.Descriptor instead.
func (FieldTypeInformation_FieldType) EnumDescriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{3, 0}
}

type ComponentDescription_DataAmount int32

const (
	ComponentDescription_ONE   ComponentDescription_DataAmount = 0
	ComponentDescription_ARRAY ComponentDescription_DataAmount = 1
)

// Enum value maps for ComponentDescription_DataAmount.
var (
	ComponentDescription_DataAmount_name = map[int32]string{
		0: "ONE",
		1: "ARRAY",
	}
	ComponentDescription_DataAmount_value = map[string]int32{
		"ONE":   0,
		"ARRAY": 1,
	}
)

func (x ComponentDescription_DataAmount) Enum() *ComponentDescription_DataAmount {
	p := new(ComponentDescription_DataAmount)
	*p = x
	return p
}

func (x ComponentDescription_DataAmount) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentDescription_DataAmount) Descriptor() protoreflect.EnumDescriptor {
	return file_components_proto_enumTypes[2].Descriptor()
}

func (ComponentDescription_DataAmount) Type() protoreflect.EnumType {
	return &file_components_proto_enumTypes[2]
}

func (x ComponentDescription_DataAmount) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentDescription_DataAmount.Descriptor instead.
func (ComponentDescription_DataAmount) EnumDescriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{6, 0}
}

// Describes the structure of the data define by the user
type ComponentStructure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields []*FieldStructure `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ComponentStructure) Reset() {
	*x = ComponentStructure{}
	mi := &file_components_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentStructure) ProtoMessage() {}

func (x *ComponentStructure) ProtoReflect() protoreflect.Message {
	mi := &file_components_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentStructure.ProtoReflect.Descriptor instead.
func (*ComponentStructure) Descriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{0}
}

func (x *ComponentStructure) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentStructure) GetFields() []*FieldStructure {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Represents a type of data that could be represented and save by the system
type FieldStructure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeInformation *FieldTypeInformation `protobuf:"bytes,2,opt,name=type_information,json=typeInformation,proto3" json:"type_information,omitempty"`
	IsNull          bool                  `protobuf:"varint,3,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty"`
	IsKey           bool                  `protobuf:"varint,4,opt,name=is_key,json=isKey,proto3" json:"is_key,omitempty"`
}

func (x *FieldStructure) Reset() {
	*x = FieldStructure{}
	mi := &file_components_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldStructure) ProtoMessage() {}

func (x *FieldStructure) ProtoReflect() protoreflect.Message {
	mi := &file_components_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldStructure.ProtoReflect.Descriptor instead.
func (*FieldStructure) Descriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{1}
}

func (x *FieldStructure) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldStructure) GetTypeInformation() *FieldTypeInformation {
	if x != nil {
		return x.TypeInformation
	}
	return nil
}

func (x *FieldStructure) GetIsNull() bool {
	if x != nil {
		return x.IsNull
	}
	return false
}

func (x *FieldStructure) GetIsKey() bool {
	if x != nil {
		return x.IsKey
	}
	return false
}

// The information necesary to reference a table
type ReferenceInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
}

func (x *ReferenceInformation) Reset() {
	*x = ReferenceInformation{}
	mi := &file_components_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceInformation) ProtoMessage() {}

func (x *ReferenceInformation) ProtoReflect() protoreflect.Message {
	mi := &file_components_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceInformation.ProtoReflect.Descriptor instead.
func (*ReferenceInformation) Descriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{2}
}

func (x *ReferenceInformation) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

// Represents the type information of the data
type FieldTypeInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type FieldTypeInformation_FieldType `protobuf:"varint,1,opt,name=type,proto3,enum=api.FieldTypeInformation_FieldType" json:"type,omitempty"`
	// Types that are assignable to Information:
	//
	//	*FieldTypeInformation_Primitive
	//	*FieldTypeInformation_Reference
	Information isFieldTypeInformation_Information `protobuf_oneof:"information"`
}

func (x *FieldTypeInformation) Reset() {
	*x = FieldTypeInformation{}
	mi := &file_components_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldTypeInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldTypeInformation) ProtoMessage() {}

func (x *FieldTypeInformation) ProtoReflect() protoreflect.Message {
	mi := &file_components_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldTypeInformation.ProtoReflect.Descriptor instead.
func (*FieldTypeInformation) Descriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{3}
}

func (x *FieldTypeInformation) GetType() FieldTypeInformation_FieldType {
	if x != nil {
		return x.Type
	}
	return FieldTypeInformation_PRIMITIVE
}

func (m *FieldTypeInformation) GetInformation() isFieldTypeInformation_Information {
	if m != nil {
		return m.Information
	}
	return nil
}

func (x *FieldTypeInformation) GetPrimitive() PrimitiveFieldType {
	if x, ok := x.GetInformation().(*FieldTypeInformation_Primitive); ok {
		return x.Primitive
	}
	return PrimitiveFieldType_INT
}

func (x *FieldTypeInformation) GetReference() *ReferenceInformation {
	if x, ok := x.GetInformation().(*FieldTypeInformation_Reference); ok {
		return x.Reference
	}
	return nil
}

type isFieldTypeInformation_Information interface {
	isFieldTypeInformation_Information()
}

type FieldTypeInformation_Primitive struct {
	Primitive PrimitiveFieldType `protobuf:"varint,2,opt,name=primitive,proto3,enum=api.PrimitiveFieldType,oneof"`
}

type FieldTypeInformation_Reference struct {
	Reference *ReferenceInformation `protobuf:"bytes,3,opt,name=reference,proto3,oneof"`
}

func (*FieldTypeInformation_Primitive) isFieldTypeInformation_Information() {}

func (*FieldTypeInformation_Reference) isFieldTypeInformation_Information() {}

// Represents the construction of a entity, that could be a Component, or a composition of components
type EntityDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Description:
	//
	//	*EntityDescription_Component
	//	*EntityDescription_Composition
	Description isEntityDescription_Description `protobuf_oneof:"description"`
}

func (x *EntityDescription) Reset() {
	*x = EntityDescription{}
	mi := &file_components_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDescription) ProtoMessage() {}

func (x *EntityDescription) ProtoReflect() protoreflect.Message {
	mi := &file_components_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDescription.ProtoReflect.Descriptor instead.
func (*EntityDescription) Descriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{4}
}

func (m *EntityDescription) GetDescription() isEntityDescription_Description {
	if m != nil {
		return m.Description
	}
	return nil
}

func (x *EntityDescription) GetComponent() *ComponentDescription {
	if x, ok := x.GetDescription().(*EntityDescription_Component); ok {
		return x.Component
	}
	return nil
}

func (x *EntityDescription) GetComposition() *ComponentCompositionDescription {
	if x, ok := x.GetDescription().(*EntityDescription_Composition); ok {
		return x.Composition
	}
	return nil
}

type isEntityDescription_Description interface {
	isEntityDescription_Description()
}

type EntityDescription_Component struct {
	Component *ComponentDescription `protobuf:"bytes,1,opt,name=component,proto3,oneof"`
}

type EntityDescription_Composition struct {
	Composition *ComponentCompositionDescription `protobuf:"bytes,2,opt,name=composition,proto3,oneof"`
}

func (*EntityDescription_Component) isEntityDescription_Description() {}

func (*EntityDescription_Composition) isEntityDescription_Description() {}

// Represents the composition of components, and it's a recursive definition
type ComponentCompositionDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*EntityDescription `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *ComponentCompositionDescription) Reset() {
	*x = ComponentCompositionDescription{}
	mi := &file_components_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentCompositionDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentCompositionDescription) ProtoMessage() {}

func (x *ComponentCompositionDescription) ProtoReflect() protoreflect.Message {
	mi := &file_components_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentCompositionDescription.ProtoReflect.Descriptor instead.
func (*ComponentCompositionDescription) Descriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{5}
}

func (x *ComponentCompositionDescription) GetEntities() []*EntityDescription {
	if x != nil {
		return x.Entities
	}
	return nil
}

// Represents the data of the component
type ComponentDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount ComponentDescription_DataAmount `protobuf:"varint,2,opt,name=amount,proto3,enum=api.ComponentDescription_DataAmount" json:"amount,omitempty"`
	Rows   int32                           `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Fields []*FieldDescription             `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ComponentDescription) Reset() {
	*x = ComponentDescription{}
	mi := &file_components_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentDescription) ProtoMessage() {}

func (x *ComponentDescription) ProtoReflect() protoreflect.Message {
	mi := &file_components_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentDescription.ProtoReflect.Descriptor instead.
func (*ComponentDescription) Descriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{6}
}

func (x *ComponentDescription) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentDescription) GetAmount() ComponentDescription_DataAmount {
	if x != nil {
		return x.Amount
	}
	return ComponentDescription_ONE
}

func (x *ComponentDescription) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ComponentDescription) GetFields() []*FieldDescription {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Represents the data of a field in a query result (array of values)
type FieldDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeInformation *FieldTypeInformation `protobuf:"bytes,2,opt,name=type_information,json=typeInformation,proto3" json:"type_information,omitempty"`
	// This should be all of the same type. This is to save space and
	// not have the type information in the FieldData
	//
	// Types that are assignable to Data:
	//
	//	*FieldDescription_Point
	//	*FieldDescription_Array
	Data isFieldDescription_Data `protobuf_oneof:"data"`
}

func (x *FieldDescription) Reset() {
	*x = FieldDescription{}
	mi := &file_components_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDescription) ProtoMessage() {}

func (x *FieldDescription) ProtoReflect() protoreflect.Message {
	mi := &file_components_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDescription.ProtoReflect.Descriptor instead.
func (*FieldDescription) Descriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{7}
}

func (x *FieldDescription) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldDescription) GetTypeInformation() *FieldTypeInformation {
	if x != nil {
		return x.TypeInformation
	}
	return nil
}

func (m *FieldDescription) GetData() isFieldDescription_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *FieldDescription) GetPoint() *FieldDescription_FieldData {
	if x, ok := x.GetData().(*FieldDescription_Point); ok {
		return x.Point
	}
	return nil
}

func (x *FieldDescription) GetArray() *FieldDescription_FieldDataArray {
	if x, ok := x.GetData().(*FieldDescription_Array); ok {
		return x.Array
	}
	return nil
}

type isFieldDescription_Data interface {
	isFieldDescription_Data()
}

type FieldDescription_Point struct {
	Point *FieldDescription_FieldData `protobuf:"bytes,3,opt,name=point,proto3,oneof"`
}

type FieldDescription_Array struct {
	Array *FieldDescription_FieldDataArray `protobuf:"bytes,4,opt,name=array,proto3,oneof"`
}

func (*FieldDescription_Point) isFieldDescription_Data() {}

func (*FieldDescription_Array) isFieldDescription_Data() {}

// If the type is primitive, then the data is store as that, but
// if the type is a reference, then is ComponentDescription
type FieldDescription_ConcreteFieldData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*FieldDescription_ConcreteFieldData_Number
	//	*FieldDescription_ConcreteFieldData_Text
	//	*FieldDescription_ConcreteFieldData_Character
	//	*FieldDescription_ConcreteFieldData_Boolean
	//	*FieldDescription_ConcreteFieldData_Date
	//	*FieldDescription_ConcreteFieldData_Reference
	Data isFieldDescription_ConcreteFieldData_Data `protobuf_oneof:"data"`
}

func (x *FieldDescription_ConcreteFieldData) Reset() {
	*x = FieldDescription_ConcreteFieldData{}
	mi := &file_components_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDescription_ConcreteFieldData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDescription_ConcreteFieldData) ProtoMessage() {}

func (x *FieldDescription_ConcreteFieldData) ProtoReflect() protoreflect.Message {
	mi := &file_components_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDescription_ConcreteFieldData.ProtoReflect.Descriptor instead.
func (*FieldDescription_ConcreteFieldData) Descriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{7, 0}
}

func (m *FieldDescription_ConcreteFieldData) GetData() isFieldDescription_ConcreteFieldData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *FieldDescription_ConcreteFieldData) GetNumber() int32 {
	if x, ok := x.GetData().(*FieldDescription_ConcreteFieldData_Number); ok {
		return x.Number
	}
	return 0
}

func (x *FieldDescription_ConcreteFieldData) GetText() string {
	if x, ok := x.GetData().(*FieldDescription_ConcreteFieldData_Text); ok {
		return x.Text
	}
	return ""
}

func (x *FieldDescription_ConcreteFieldData) GetCharacter() string {
	if x, ok := x.GetData().(*FieldDescription_ConcreteFieldData_Character); ok {
		return x.Character
	}
	return ""
}

func (x *FieldDescription_ConcreteFieldData) GetBoolean() bool {
	if x, ok := x.GetData().(*FieldDescription_ConcreteFieldData_Boolean); ok {
		return x.Boolean
	}
	return false
}

func (x *FieldDescription_ConcreteFieldData) GetDate() uint32 {
	if x, ok := x.GetData().(*FieldDescription_ConcreteFieldData_Date); ok {
		return x.Date
	}
	return 0
}

func (x *FieldDescription_ConcreteFieldData) GetReference() *ComponentDescription {
	if x, ok := x.GetData().(*FieldDescription_ConcreteFieldData_Reference); ok {
		return x.Reference
	}
	return nil
}

type isFieldDescription_ConcreteFieldData_Data interface {
	isFieldDescription_ConcreteFieldData_Data()
}

type FieldDescription_ConcreteFieldData_Number struct {
	Number int32 `protobuf:"varint,1,opt,name=number,proto3,oneof"`
}

type FieldDescription_ConcreteFieldData_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type FieldDescription_ConcreteFieldData_Character struct {
	Character string `protobuf:"bytes,3,opt,name=character,proto3,oneof"`
}

type FieldDescription_ConcreteFieldData_Boolean struct {
	Boolean bool `protobuf:"varint,4,opt,name=boolean,proto3,oneof"`
}

type FieldDescription_ConcreteFieldData_Date struct {
	Date uint32 `protobuf:"varint,5,opt,name=date,proto3,oneof"`
}

type FieldDescription_ConcreteFieldData_Reference struct {
	Reference *ComponentDescription `protobuf:"bytes,6,opt,name=reference,proto3,oneof"`
}

func (*FieldDescription_ConcreteFieldData_Number) isFieldDescription_ConcreteFieldData_Data() {}

func (*FieldDescription_ConcreteFieldData_Text) isFieldDescription_ConcreteFieldData_Data() {}

func (*FieldDescription_ConcreteFieldData_Character) isFieldDescription_ConcreteFieldData_Data() {}

func (*FieldDescription_ConcreteFieldData_Boolean) isFieldDescription_ConcreteFieldData_Data() {}

func (*FieldDescription_ConcreteFieldData_Date) isFieldDescription_ConcreteFieldData_Data() {}

func (*FieldDescription_ConcreteFieldData_Reference) isFieldDescription_ConcreteFieldData_Data() {}

type FieldDescription_NullableFieldData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *FieldDescription_ConcreteFieldData `protobuf:"bytes,1,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *FieldDescription_NullableFieldData) Reset() {
	*x = FieldDescription_NullableFieldData{}
	mi := &file_components_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDescription_NullableFieldData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDescription_NullableFieldData) ProtoMessage() {}

func (x *FieldDescription_NullableFieldData) ProtoReflect() protoreflect.Message {
	mi := &file_components_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDescription_NullableFieldData.ProtoReflect.Descriptor instead.
func (*FieldDescription_NullableFieldData) Descriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{7, 1}
}

func (x *FieldDescription_NullableFieldData) GetData() *FieldDescription_ConcreteFieldData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FieldDescription_FieldData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*FieldDescription_FieldData_Concrete
	//	*FieldDescription_FieldData_Nullable
	Data isFieldDescription_FieldData_Data `protobuf_oneof:"data"`
}

func (x *FieldDescription_FieldData) Reset() {
	*x = FieldDescription_FieldData{}
	mi := &file_components_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDescription_FieldData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDescription_FieldData) ProtoMessage() {}

func (x *FieldDescription_FieldData) ProtoReflect() protoreflect.Message {
	mi := &file_components_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDescription_FieldData.ProtoReflect.Descriptor instead.
func (*FieldDescription_FieldData) Descriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{7, 2}
}

func (m *FieldDescription_FieldData) GetData() isFieldDescription_FieldData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *FieldDescription_FieldData) GetConcrete() *FieldDescription_ConcreteFieldData {
	if x, ok := x.GetData().(*FieldDescription_FieldData_Concrete); ok {
		return x.Concrete
	}
	return nil
}

func (x *FieldDescription_FieldData) GetNullable() *FieldDescription_NullableFieldData {
	if x, ok := x.GetData().(*FieldDescription_FieldData_Nullable); ok {
		return x.Nullable
	}
	return nil
}

type isFieldDescription_FieldData_Data interface {
	isFieldDescription_FieldData_Data()
}

type FieldDescription_FieldData_Concrete struct {
	Concrete *FieldDescription_ConcreteFieldData `protobuf:"bytes,1,opt,name=concrete,proto3,oneof"`
}

type FieldDescription_FieldData_Nullable struct {
	Nullable *FieldDescription_NullableFieldData `protobuf:"bytes,2,opt,name=nullable,proto3,oneof"`
}

func (*FieldDescription_FieldData_Concrete) isFieldDescription_FieldData_Data() {}

func (*FieldDescription_FieldData_Nullable) isFieldDescription_FieldData_Data() {}

type FieldDescription_FieldDataArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataArray []*FieldDescription_FieldData `protobuf:"bytes,1,rep,name=data_array,json=dataArray,proto3" json:"data_array,omitempty"`
}

func (x *FieldDescription_FieldDataArray) Reset() {
	*x = FieldDescription_FieldDataArray{}
	mi := &file_components_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDescription_FieldDataArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDescription_FieldDataArray) ProtoMessage() {}

func (x *FieldDescription_FieldDataArray) ProtoReflect() protoreflect.Message {
	mi := &file_components_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDescription_FieldDataArray.ProtoReflect.Descriptor instead.
func (*FieldDescription_FieldDataArray) Descriptor() ([]byte, []int) {
	return file_components_proto_rawDescGZIP(), []int{7, 3}
}

func (x *FieldDescription_FieldDataArray) GetDataArray() []*FieldDescription_FieldData {
	if x != nil {
		return x.DataArray
	}
	return nil
}

var File_components_proto protoreflect.FileDescriptor

var file_components_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x55, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x2b, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x9a,
	0x01, 0x0a, 0x0e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x10, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x74, 0x79, 0x70, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x69,
	0x73, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73,
	0x4e, 0x75, 0x6c, 0x6c, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x4b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x14, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0xfd, 0x01, 0x0a, 0x14, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72,
	0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x48, 0x00, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x12, 0x39, 0x0a,
	0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x29, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x52, 0x49, 0x4d, 0x49, 0x54, 0x49,
	0x56, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x46, 0x45, 0x52, 0x45, 0x4e, 0x43,
	0x45, 0x10, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xa7, 0x01, 0x0a, 0x11, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x12, 0x48, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00,
	0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0d, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x55, 0x0a, 0x1f,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x32, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x22, 0xcd, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x3c, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f,
	0x77, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x22, 0x20, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x07, 0x0a, 0x03, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x52, 0x52, 0x41,
	0x59, 0x10, 0x01, 0x22, 0x9c, 0x06, 0x0a, 0x10, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x10,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0f, 0x74, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x05, 0x61,
	0x72, 0x72, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x61, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x48, 0x00, 0x52, 0x05, 0x61, 0x72, 0x72, 0x61, 0x79, 0x1a, 0xd8, 0x01, 0x0a, 0x11, 0x43, 0x6f,
	0x6e, 0x63, 0x72, 0x65, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x18, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x00, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x1e, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x12, 0x14, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x39, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x06, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x5e, 0x0a, 0x11, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x40, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43,
	0x6f, 0x6e, 0x63, 0x72, 0x65, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0xa1, 0x01, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x45, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x63, 0x72, 0x65, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x63,
	0x72, 0x65, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52,
	0x08, 0x63, 0x6f, 0x6e, 0x63, 0x72, 0x65, 0x74, 0x65, 0x12, 0x45, 0x0a, 0x08, 0x6e, 0x75, 0x6c,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x50, 0x0a, 0x0e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x3e, 0x0a, 0x0a, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x09, 0x64, 0x61, 0x74, 0x61, 0x41, 0x72, 0x72, 0x61, 0x79, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x2a, 0x93, 0x01, 0x0a, 0x12, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x54,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x43, 0x48, 0x41, 0x52, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c,
	0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x45, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08,
	0x4e, 0x55, 0x4c, 0x4c, 0x5f, 0x49, 0x4e, 0x54, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x55,
	0x4c, 0x4c, 0x5f, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09, 0x4e,
	0x55, 0x4c, 0x4c, 0x5f, 0x43, 0x48, 0x41, 0x52, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x55,
	0x4c, 0x4c, 0x5f, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x55, 0x4c,
	0x4c, 0x5f, 0x44, 0x41, 0x54, 0x45, 0x10, 0x09, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x75, 0x61, 0x6e, 0x42, 0x69, 0x61, 0x6e, 0x63,
	0x75, 0x7a, 0x7a, 0x6f, 0x2f, 0x6f, 0x77, 0x6e, 0x5f, 0x77, 0x69, 0x6b, 0x69, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_components_proto_rawDescOnce sync.Once
	file_components_proto_rawDescData = file_components_proto_rawDesc
)

func file_components_proto_rawDescGZIP() []byte {
	file_components_proto_rawDescOnce.Do(func() {
		file_components_proto_rawDescData = protoimpl.X.CompressGZIP(file_components_proto_rawDescData)
	})
	return file_components_proto_rawDescData
}

var file_components_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_components_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_components_proto_goTypes = []any{
	(PrimitiveFieldType)(0),                    // 0: api.PrimitiveFieldType
	(FieldTypeInformation_FieldType)(0),        // 1: api.FieldTypeInformation.FieldType
	(ComponentDescription_DataAmount)(0),       // 2: api.ComponentDescription.DataAmount
	(*ComponentStructure)(nil),                 // 3: api.ComponentStructure
	(*FieldStructure)(nil),                     // 4: api.FieldStructure
	(*ReferenceInformation)(nil),               // 5: api.ReferenceInformation
	(*FieldTypeInformation)(nil),               // 6: api.FieldTypeInformation
	(*EntityDescription)(nil),                  // 7: api.EntityDescription
	(*ComponentCompositionDescription)(nil),    // 8: api.ComponentCompositionDescription
	(*ComponentDescription)(nil),               // 9: api.ComponentDescription
	(*FieldDescription)(nil),                   // 10: api.FieldDescription
	(*FieldDescription_ConcreteFieldData)(nil), // 11: api.FieldDescription.ConcreteFieldData
	(*FieldDescription_NullableFieldData)(nil), // 12: api.FieldDescription.NullableFieldData
	(*FieldDescription_FieldData)(nil),         // 13: api.FieldDescription.FieldData
	(*FieldDescription_FieldDataArray)(nil),    // 14: api.FieldDescription.FieldDataArray
}
var file_components_proto_depIdxs = []int32{
	4,  // 0: api.ComponentStructure.fields:type_name -> api.FieldStructure
	6,  // 1: api.FieldStructure.type_information:type_name -> api.FieldTypeInformation
	1,  // 2: api.FieldTypeInformation.type:type_name -> api.FieldTypeInformation.FieldType
	0,  // 3: api.FieldTypeInformation.primitive:type_name -> api.PrimitiveFieldType
	5,  // 4: api.FieldTypeInformation.reference:type_name -> api.ReferenceInformation
	9,  // 5: api.EntityDescription.component:type_name -> api.ComponentDescription
	8,  // 6: api.EntityDescription.composition:type_name -> api.ComponentCompositionDescription
	7,  // 7: api.ComponentCompositionDescription.entities:type_name -> api.EntityDescription
	2,  // 8: api.ComponentDescription.amount:type_name -> api.ComponentDescription.DataAmount
	10, // 9: api.ComponentDescription.fields:type_name -> api.FieldDescription
	6,  // 10: api.FieldDescription.type_information:type_name -> api.FieldTypeInformation
	13, // 11: api.FieldDescription.point:type_name -> api.FieldDescription.FieldData
	14, // 12: api.FieldDescription.array:type_name -> api.FieldDescription.FieldDataArray
	9,  // 13: api.FieldDescription.ConcreteFieldData.reference:type_name -> api.ComponentDescription
	11, // 14: api.FieldDescription.NullableFieldData.data:type_name -> api.FieldDescription.ConcreteFieldData
	11, // 15: api.FieldDescription.FieldData.concrete:type_name -> api.FieldDescription.ConcreteFieldData
	12, // 16: api.FieldDescription.FieldData.nullable:type_name -> api.FieldDescription.NullableFieldData
	13, // 17: api.FieldDescription.FieldDataArray.data_array:type_name -> api.FieldDescription.FieldData
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_components_proto_init() }
func file_components_proto_init() {
	if File_components_proto != nil {
		return
	}
	file_components_proto_msgTypes[3].OneofWrappers = []any{
		(*FieldTypeInformation_Primitive)(nil),
		(*FieldTypeInformation_Reference)(nil),
	}
	file_components_proto_msgTypes[4].OneofWrappers = []any{
		(*EntityDescription_Component)(nil),
		(*EntityDescription_Composition)(nil),
	}
	file_components_proto_msgTypes[7].OneofWrappers = []any{
		(*FieldDescription_Point)(nil),
		(*FieldDescription_Array)(nil),
	}
	file_components_proto_msgTypes[8].OneofWrappers = []any{
		(*FieldDescription_ConcreteFieldData_Number)(nil),
		(*FieldDescription_ConcreteFieldData_Text)(nil),
		(*FieldDescription_ConcreteFieldData_Character)(nil),
		(*FieldDescription_ConcreteFieldData_Boolean)(nil),
		(*FieldDescription_ConcreteFieldData_Date)(nil),
		(*FieldDescription_ConcreteFieldData_Reference)(nil),
	}
	file_components_proto_msgTypes[9].OneofWrappers = []any{}
	file_components_proto_msgTypes[10].OneofWrappers = []any{
		(*FieldDescription_FieldData_Concrete)(nil),
		(*FieldDescription_FieldData_Nullable)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_components_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_proto_goTypes,
		DependencyIndexes: file_components_proto_depIdxs,
		EnumInfos:         file_components_proto_enumTypes,
		MessageInfos:      file_components_proto_msgTypes,
	}.Build()
	File_components_proto = out.File
	file_components_proto_rawDesc = nil
	file_components_proto_goTypes = nil
	file_components_proto_depIdxs = nil
}
