// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: own_wiki.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserInteraction_LoadPlugin_FullMethodName         = "/api.UserInteraction/LoadPlugin"
	UserInteraction_RegisterComponents_FullMethodName = "/api.UserInteraction/RegisterComponents"
	UserInteraction_ImportFiles_FullMethodName        = "/api.UserInteraction/ImportFiles"
	UserInteraction_Render_FullMethodName             = "/api.UserInteraction/Render"
)

// UserInteractionClient is the client API for UserInteraction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserInteractionClient interface {
	// Loads the user code given by a path
	LoadPlugin(ctx context.Context, in *LoadPluginRequest, opts ...grpc.CallOption) (*Empty, error)
	// Lets the user define structures to sava the data
	RegisterComponents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RegisterComponentsResponse, error)
	// Lets the user load data from files and returns the component data
	ImportFiles(ctx context.Context, opts ...grpc.CallOption) (UserInteraction_ImportFilesClient, error)
	// Lets the user render the data, and changes its behaviour given the events of the system
	Render(ctx context.Context, opts ...grpc.CallOption) (UserInteraction_RenderClient, error)
}

type userInteractionClient struct {
	cc grpc.ClientConnInterface
}

func NewUserInteractionClient(cc grpc.ClientConnInterface) UserInteractionClient {
	return &userInteractionClient{cc}
}

func (c *userInteractionClient) LoadPlugin(ctx context.Context, in *LoadPluginRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, UserInteraction_LoadPlugin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInteractionClient) RegisterComponents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RegisterComponentsResponse, error) {
	out := new(RegisterComponentsResponse)
	err := c.cc.Invoke(ctx, UserInteraction_RegisterComponents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInteractionClient) ImportFiles(ctx context.Context, opts ...grpc.CallOption) (UserInteraction_ImportFilesClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserInteraction_ServiceDesc.Streams[0], UserInteraction_ImportFiles_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &userInteractionImportFilesClient{stream}
	return x, nil
}

type UserInteraction_ImportFilesClient interface {
	Send(*ImportedFilesRequest) error
	Recv() (*ImportFilesResponse, error)
	grpc.ClientStream
}

type userInteractionImportFilesClient struct {
	grpc.ClientStream
}

func (x *userInteractionImportFilesClient) Send(m *ImportedFilesRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userInteractionImportFilesClient) Recv() (*ImportFilesResponse, error) {
	m := new(ImportFilesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userInteractionClient) Render(ctx context.Context, opts ...grpc.CallOption) (UserInteraction_RenderClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserInteraction_ServiceDesc.Streams[1], UserInteraction_Render_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &userInteractionRenderClient{stream}
	return x, nil
}

type UserInteraction_RenderClient interface {
	Send(*RenderRequest) error
	Recv() (*RenderResponse, error)
	grpc.ClientStream
}

type userInteractionRenderClient struct {
	grpc.ClientStream
}

func (x *userInteractionRenderClient) Send(m *RenderRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userInteractionRenderClient) Recv() (*RenderResponse, error) {
	m := new(RenderResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserInteractionServer is the server API for UserInteraction service.
// All implementations must embed UnimplementedUserInteractionServer
// for forward compatibility
type UserInteractionServer interface {
	// Loads the user code given by a path
	LoadPlugin(context.Context, *LoadPluginRequest) (*Empty, error)
	// Lets the user define structures to sava the data
	RegisterComponents(context.Context, *Empty) (*RegisterComponentsResponse, error)
	// Lets the user load data from files and returns the component data
	ImportFiles(UserInteraction_ImportFilesServer) error
	// Lets the user render the data, and changes its behaviour given the events of the system
	Render(UserInteraction_RenderServer) error
	mustEmbedUnimplementedUserInteractionServer()
}

// UnimplementedUserInteractionServer must be embedded to have forward compatible implementations.
type UnimplementedUserInteractionServer struct {
}

func (UnimplementedUserInteractionServer) LoadPlugin(context.Context, *LoadPluginRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadPlugin not implemented")
}
func (UnimplementedUserInteractionServer) RegisterComponents(context.Context, *Empty) (*RegisterComponentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterComponents not implemented")
}
func (UnimplementedUserInteractionServer) ImportFiles(UserInteraction_ImportFilesServer) error {
	return status.Errorf(codes.Unimplemented, "method ImportFiles not implemented")
}
func (UnimplementedUserInteractionServer) Render(UserInteraction_RenderServer) error {
	return status.Errorf(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedUserInteractionServer) mustEmbedUnimplementedUserInteractionServer() {}

// UnsafeUserInteractionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserInteractionServer will
// result in compilation errors.
type UnsafeUserInteractionServer interface {
	mustEmbedUnimplementedUserInteractionServer()
}

func RegisterUserInteractionServer(s grpc.ServiceRegistrar, srv UserInteractionServer) {
	s.RegisterService(&UserInteraction_ServiceDesc, srv)
}

func _UserInteraction_LoadPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInteractionServer).LoadPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserInteraction_LoadPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInteractionServer).LoadPlugin(ctx, req.(*LoadPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInteraction_RegisterComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInteractionServer).RegisterComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserInteraction_RegisterComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInteractionServer).RegisterComponents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInteraction_ImportFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserInteractionServer).ImportFiles(&userInteractionImportFilesServer{stream})
}

type UserInteraction_ImportFilesServer interface {
	Send(*ImportFilesResponse) error
	Recv() (*ImportedFilesRequest, error)
	grpc.ServerStream
}

type userInteractionImportFilesServer struct {
	grpc.ServerStream
}

func (x *userInteractionImportFilesServer) Send(m *ImportFilesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userInteractionImportFilesServer) Recv() (*ImportedFilesRequest, error) {
	m := new(ImportedFilesRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UserInteraction_Render_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserInteractionServer).Render(&userInteractionRenderServer{stream})
}

type UserInteraction_RenderServer interface {
	Send(*RenderResponse) error
	Recv() (*RenderRequest, error)
	grpc.ServerStream
}

type userInteractionRenderServer struct {
	grpc.ServerStream
}

func (x *userInteractionRenderServer) Send(m *RenderResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userInteractionRenderServer) Recv() (*RenderRequest, error) {
	m := new(RenderRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserInteraction_ServiceDesc is the grpc.ServiceDesc for UserInteraction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserInteraction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.UserInteraction",
	HandlerType: (*UserInteractionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadPlugin",
			Handler:    _UserInteraction_LoadPlugin_Handler,
		},
		{
			MethodName: "RegisterComponents",
			Handler:    _UserInteraction_RegisterComponents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ImportFiles",
			Handler:       _UserInteraction_ImportFiles_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Render",
			Handler:       _UserInteraction_Render_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "own_wiki.proto",
}

const (
	SystemInteraction_Query_FullMethodName     = "/api.SystemInteraction/Query"
	SystemInteraction_SendEvent_FullMethodName = "/api.SystemInteraction/SendEvent"
)

// SystemInteractionClient is the client API for SystemInteraction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemInteractionClient interface {
	// Lets the system send the data to the user, that was save
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Lets the system receive events that are generated by the user
	SendEvent(ctx context.Context, in *SendEventRequest, opts ...grpc.CallOption) (*Empty, error)
}

type systemInteractionClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemInteractionClient(cc grpc.ClientConnInterface) SystemInteractionClient {
	return &systemInteractionClient{cc}
}

func (c *systemInteractionClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, SystemInteraction_Query_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemInteractionClient) SendEvent(ctx context.Context, in *SendEventRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, SystemInteraction_SendEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemInteractionServer is the server API for SystemInteraction service.
// All implementations must embed UnimplementedSystemInteractionServer
// for forward compatibility
type SystemInteractionServer interface {
	// Lets the system send the data to the user, that was save
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Lets the system receive events that are generated by the user
	SendEvent(context.Context, *SendEventRequest) (*Empty, error)
	mustEmbedUnimplementedSystemInteractionServer()
}

// UnimplementedSystemInteractionServer must be embedded to have forward compatible implementations.
type UnimplementedSystemInteractionServer struct {
}

func (UnimplementedSystemInteractionServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedSystemInteractionServer) SendEvent(context.Context, *SendEventRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedSystemInteractionServer) mustEmbedUnimplementedSystemInteractionServer() {}

// UnsafeSystemInteractionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemInteractionServer will
// result in compilation errors.
type UnsafeSystemInteractionServer interface {
	mustEmbedUnimplementedSystemInteractionServer()
}

func RegisterSystemInteractionServer(s grpc.ServiceRegistrar, srv SystemInteractionServer) {
	s.RegisterService(&SystemInteraction_ServiceDesc, srv)
}

func _SystemInteraction_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemInteractionServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemInteraction_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemInteractionServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemInteraction_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemInteractionServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemInteraction_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemInteractionServer).SendEvent(ctx, req.(*SendEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemInteraction_ServiceDesc is the grpc.ServiceDesc for SystemInteraction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemInteraction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.SystemInteraction",
	HandlerType: (*SystemInteractionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _SystemInteraction_Query_Handler,
		},
		{
			MethodName: "SendEvent",
			Handler:    _SystemInteraction_SendEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "own_wiki.proto",
}
