// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: scene.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the information like the frame count, etc.
type FrameInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameCount uint32 `protobuf:"varint,1,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
}

func (x *FrameInformation) Reset() {
	*x = FrameInformation{}
	mi := &file_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameInformation) ProtoMessage() {}

func (x *FrameInformation) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameInformation.ProtoReflect.Descriptor instead.
func (*FrameInformation) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{0}
}

func (x *FrameInformation) GetFrameCount() uint32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

// Represents the description of the scene in a agnostic way
type SceneDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MainCamera *Camera `protobuf:"bytes,1,opt,name=main_camera,json=mainCamera,proto3" json:"main_camera,omitempty"`
}

func (x *SceneDescription) Reset() {
	*x = SceneDescription{}
	mi := &file_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneDescription) ProtoMessage() {}

func (x *SceneDescription) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneDescription.ProtoReflect.Descriptor instead.
func (*SceneDescription) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{1}
}

func (x *SceneDescription) GetMainCamera() *Camera {
	if x != nil {
		return x.MainCamera
	}
	return nil
}

// Its the way to capture the perspective of the objects
type Camera struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Perspective  *Camera_PerspectiveMatrix `protobuf:"bytes,1,opt,name=perspective,proto3" json:"perspective,omitempty"`
	ScreenLayout *Layout                   `protobuf:"bytes,2,opt,name=screen_layout,json=screenLayout,proto3" json:"screen_layout,omitempty"`
}

func (x *Camera) Reset() {
	*x = Camera{}
	mi := &file_scene_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Camera) ProtoMessage() {}

func (x *Camera) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Camera.ProtoReflect.Descriptor instead.
func (*Camera) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{2}
}

func (x *Camera) GetPerspective() *Camera_PerspectiveMatrix {
	if x != nil {
		return x.Perspective
	}
	return nil
}

func (x *Camera) GetScreenLayout() *Layout {
	if x != nil {
		return x.ScreenLayout
	}
	return nil
}

// Represents a group of objects that
type Layout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []*SceneObject `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *Layout) Reset() {
	*x = Layout{}
	mi := &file_scene_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layout) ProtoMessage() {}

func (x *Layout) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layout.ProtoReflect.Descriptor instead.
func (*Layout) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{3}
}

func (x *Layout) GetObjects() []*SceneObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

// All the objects that could be define, are define here
type SceneObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Object:
	//
	//	*SceneObject_Text
	//	*SceneObject_ImageInfo
	Object isSceneObject_Object `protobuf_oneof:"object"`
}

func (x *SceneObject) Reset() {
	*x = SceneObject{}
	mi := &file_scene_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneObject) ProtoMessage() {}

func (x *SceneObject) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneObject.ProtoReflect.Descriptor instead.
func (*SceneObject) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{4}
}

func (m *SceneObject) GetObject() isSceneObject_Object {
	if m != nil {
		return m.Object
	}
	return nil
}

func (x *SceneObject) GetText() string {
	if x, ok := x.GetObject().(*SceneObject_Text); ok {
		return x.Text
	}
	return ""
}

func (x *SceneObject) GetImageInfo() *SceneObject_Image {
	if x, ok := x.GetObject().(*SceneObject_ImageInfo); ok {
		return x.ImageInfo
	}
	return nil
}

type isSceneObject_Object interface {
	isSceneObject_Object()
}

type SceneObject_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type SceneObject_ImageInfo struct {
	ImageInfo *SceneObject_Image `protobuf:"bytes,2,opt,name=image_info,json=imageInfo,proto3,oneof"`
}

func (*SceneObject_Text) isSceneObject_Object() {}

func (*SceneObject_ImageInfo) isSceneObject_Object() {}

// The perspective matrix is a R^(4x4)
type Camera_PerspectiveMatrix struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []float32 `protobuf:"fixed32,1,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *Camera_PerspectiveMatrix) Reset() {
	*x = Camera_PerspectiveMatrix{}
	mi := &file_scene_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Camera_PerspectiveMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Camera_PerspectiveMatrix) ProtoMessage() {}

func (x *Camera_PerspectiveMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Camera_PerspectiveMatrix.ProtoReflect.Descriptor instead.
func (*Camera_PerspectiveMatrix) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Camera_PerspectiveMatrix) GetValue() []float32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type SceneObject_Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url   string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *SceneObject_Image) Reset() {
	*x = SceneObject_Image{}
	mi := &file_scene_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneObject_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneObject_Image) ProtoMessage() {}

func (x *SceneObject_Image) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneObject_Image.ProtoReflect.Descriptor instead.
func (*SceneObject_Image) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SceneObject_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SceneObject_Image) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_scene_proto protoreflect.FileDescriptor

var file_scene_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61,
	0x70, 0x69, 0x22, 0x33, 0x0a, 0x10, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x10, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x0b, 0x6d,
	0x61, 0x69, 0x6e, 0x5f, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x0a, 0x6d,
	0x61, 0x69, 0x6e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x22, 0xa6, 0x01, 0x0a, 0x06, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x12, 0x3f, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x73, 0x70, 0x65, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x30, 0x0a, 0x0d, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x5f,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x0c, 0x73, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x1a, 0x29, 0x0a, 0x11, 0x50, 0x65, 0x72, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x34, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x07,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x0b, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x37,
	0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x09, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x2f, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x4a, 0x75, 0x61, 0x6e, 0x42, 0x69, 0x61, 0x6e, 0x63, 0x75, 0x7a, 0x7a, 0x6f, 0x2f, 0x6f,
	0x77, 0x6e, 0x5f, 0x77, 0x69, 0x6b, 0x69, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scene_proto_rawDescOnce sync.Once
	file_scene_proto_rawDescData = file_scene_proto_rawDesc
)

func file_scene_proto_rawDescGZIP() []byte {
	file_scene_proto_rawDescOnce.Do(func() {
		file_scene_proto_rawDescData = protoimpl.X.CompressGZIP(file_scene_proto_rawDescData)
	})
	return file_scene_proto_rawDescData
}

var file_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_scene_proto_goTypes = []any{
	(*FrameInformation)(nil),         // 0: api.FrameInformation
	(*SceneDescription)(nil),         // 1: api.SceneDescription
	(*Camera)(nil),                   // 2: api.Camera
	(*Layout)(nil),                   // 3: api.Layout
	(*SceneObject)(nil),              // 4: api.SceneObject
	(*Camera_PerspectiveMatrix)(nil), // 5: api.Camera.PerspectiveMatrix
	(*SceneObject_Image)(nil),        // 6: api.SceneObject.Image
}
var file_scene_proto_depIdxs = []int32{
	2, // 0: api.SceneDescription.main_camera:type_name -> api.Camera
	5, // 1: api.Camera.perspective:type_name -> api.Camera.PerspectiveMatrix
	3, // 2: api.Camera.screen_layout:type_name -> api.Layout
	4, // 3: api.Layout.objects:type_name -> api.SceneObject
	6, // 4: api.SceneObject.image_info:type_name -> api.SceneObject.Image
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_scene_proto_init() }
func file_scene_proto_init() {
	if File_scene_proto != nil {
		return
	}
	file_scene_proto_msgTypes[4].OneofWrappers = []any{
		(*SceneObject_Text)(nil),
		(*SceneObject_ImageInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scene_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scene_proto_goTypes,
		DependencyIndexes: file_scene_proto_depIdxs,
		MessageInfos:      file_scene_proto_msgTypes,
	}.Build()
	File_scene_proto = out.File
	file_scene_proto_rawDesc = nil
	file_scene_proto_goTypes = nil
	file_scene_proto_depIdxs = nil
}
