syntax = "proto3";
package api;

option go_package = "github.com/JuanBiancuzzo/own_wiki/core"; 

// Represents the information needed (and sometimes optional) to render a frame
message FrameInformation {
    // The amount of pixels asign to the horizontal direction
    uint32 resolution_x = 1;
    // The amount of pixels asign to the vertical direction
    uint32 resolution_y = 2;
	// The time in seconds from the first call to the view 
    float time = 3;
	// The delta time between frames
    float dtime = 4;
	// The framerate (it would be a fix framerate for now)
    float frame_rate = 5;
	// The amount of frames from the first call to the view
    uint32 frame_count = 6;
}

// Represents the description of the scene in a agnostic way
message SceneDescription {
    repeated CameraDescription cameras = 1;
}

// Its the way to capture the perspective of the objects
message CameraDescription {
    // The perspective matrix is a R^(4x4)
    message PerspectiveMatrix {
        repeated float value = 1;
    }

    PerspectiveMatrix perspective = 1;
    repeated DrawCommand draw_commands = 2;
}

// This represents the smallest draw to make
message DrawCommand {
    enum DrawType {
        RECTANGLE = 0;
        TEXT = 1;
    }

    DrawType type = 1;
    oneof value {
        DrawRectangle rectangle = 2;
        DrawText text = 3;
    }
}

// This describes a quad
message DrawRectangle {
    float position_x = 1;
    float position_y = 2;
    float width = 3;
    float height = 4;
    Color background = 5;
}

// This represents any text
message DrawText {
    float position_x = 1;
    float position_y = 2;
    float width = 3;
    float height = 4;
    string content = 5;
}

// This represents any type of color
message Color {
    float r = 1;
    float g = 2;
    float b = 3;
    float a = 4;
}
